name: Deploy to GitHub Pages

permissions:
  contents: write

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest

    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v4
    
    # sets up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4

    - name: install tailwind
      working-directory: ./AdventOfCode.Blazor
      run: npm install

    - name: run tailwind
      working-directory: ./AdventOfCode.Blazor
      run: npx tailwindcss -i ./Styles/app.css -o ./wwwroot/app.css
      
    - name: Restore nuget
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore

#    - name: Test project
#      run: dotnet test --no-restore

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish AdventOfCode.Blazor/AdventOfCode.Blazor.csproj -c Release -o release --nologo --no-restore

    # changes the base-tag in index.html from '/' to 'AdventOfCode' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to AdventOfCode
      run: sed -i 's/<base href="\/" \/>/<base href="\/AdventOfCode\/" \/>/g' release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
  
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot # The folder the action should deploy.
